# Generated by Django 5.2.17 on 2026-08-23 10:52

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("organization_id", models.UUIDField(db_index=True, null=True)),
                ("ticket_id", models.CharField(max_length=32)),
                ("title", models.CharField(max_length=255)),
                ("severity", models.CharField(default="medium", max_length=16)),
                ("status", models.CharField(default="open", max_length=16)),
                ("rule_id", models.UUIDField(null=True)),
                ("cause_md", models.TextField(default="")),
                ("predict_md", models.TextField(default="")),
                ("blast_radius", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="TelemetryEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("organization_id", models.UUIDField(db_index=True, null=True)),
                ("metric", models.CharField(db_index=True, default="", max_length=128)),
                ("module", models.CharField(default="", max_length=128)),
                ("value", models.FloatField(default=0.0)),
                ("latency_ms", models.FloatField(default=0.0)),
                ("status", models.CharField(default="ok", max_length=16)),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="TelemetryRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("organization_id", models.UUIDField(db_index=True, null=True)),
                ("workspace_id", models.UUIDField(null=True)),
                ("name", models.CharField(max_length=255)),
                ("source_md", models.TextField(default="")),
                ("condition", models.TextField(default="")),
                ("entities", models.JSONField(default=list)),
                ("status", models.CharField(default="draft", max_length=32)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
