# Generated by Django 5.2.16 on 2026-08-03 16:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storageobject',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='storageobject',
            index=models.Index(fields=['organization_id', '-created_at'], name='idx_storage_org_created'),
        ),
    ]
