# Generated by Django 5.2.16 on 2026-08-03 16:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_execution_engine_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['organization_id', 'status', '-created_at'], name='idx_jobs_org_status_created'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['organization_id', '-priority', '-created_at'], name='idx_jobs_org_prio_created'),
        ),
    ]
