# Generated by Django 5.2.16 on 2026-08-03 17:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('auth_method', models.CharField(choices=[('none', 'none'), ('password', 'password'), ('api_key', 'api_key'), ('oauth2', 'oauth2'), ('token', 'token')], default='password', max_length=32)),
                ('encrypted_payload', models.BinaryField()),
                ('key_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('rotated', 'Rotated'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=32)),
                ('rotation_due_at', models.DateTimeField(blank=True, null=True)),
                ('last_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='integrations.credential')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'integration_credentials',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization_id', 'status', '-created_at'], name='idx_cred_org_status_created')],
            },
        ),
    ]
