# Generated by Django 5.2.16 on 2026-08-03 18:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0004_track8_perf_indexes'),
        ('integrations', '0001_credential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('connector_type', models.CharField(db_index=True, max_length=128)),
                ('connector_version', models.CharField(default='1.0.0', max_length=32)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('health_status', models.CharField(choices=[('unknown', 'Unknown'), ('testing', 'Testing'), ('healthy', 'Healthy'), ('unhealthy', 'Unhealthy')], db_index=True, default='unknown', max_length=32)),
                ('last_health_message', models.TextField(blank=True, default='')),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('next_sync_at', models.DateTimeField(blank=True, null=True)),
                ('schema_version', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('sync_schedule', models.CharField(default='manual', max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connections', to='integrations.credential')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_connections', to=settings.AUTH_USER_MODEL)),
                ('target_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_connections', to='datasets.dataset')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'integration_connections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization_id', 'workspace_id', '-created_at'], name='idx_conn_org_ws_created'), models.Index(fields=['organization_id', 'health_status'], name='idx_conn_org_health')],
            },
        ),
    ]
