# Generated by Django 5.2.16 on 2026-08-03 18:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0004_track8_perf_indexes'),
        ('integrations', '0003_schema_snapshot'),
        ('jobs', '0003_track8_perf_indexes'),
        ('storage', '0002_track8_perf_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('mode', models.CharField(choices=[('full', 'Full'), ('incremental', 'Incremental')], default='full', max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=32)),
                ('rows_extracted', models.PositiveIntegerField(default=0)),
                ('rows_loaded', models.PositiveIntegerField(default=0)),
                ('cursor_state', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='integrations.connection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_runs', to='datasets.dataset')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_runs', to='jobs.job')),
                ('storage_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_runs', to='storage.storageobject')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'integration_sync_runs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['connection', '-created_at'], name='idx_sync_run_conn_created'), models.Index(fields=['organization_id', 'status', '-created_at'], name='idx_sync_run_org_status')],
            },
        ),
    ]
