# Generated by Django 5.2.16 on 2026-08-04 15:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0004_track8_perf_indexes'),
        ('jobs', '0003_track8_perf_indexes'),
        ('storage', '0002_track8_perf_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('version_number', models.PositiveIntegerField()),
                ('schema', models.JSONField(blank=True, default=dict)),
                ('row_count', models.BigIntegerField(blank=True, null=True)),
                ('checksum_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('change_summary', models.TextField(blank=True, default='')),
                ('source_layer', models.CharField(choices=[('landing', 'Landing Zone'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='landing', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='datasets.dataset')),
                ('storage_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset_versions', to='storage.storageobject')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_platform_dataset_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='LayerArtifact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('layer', models.CharField(choices=[('landing', 'Landing Zone'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], db_index=True, max_length=16)),
                ('row_count', models.BigIntegerField(blank=True, null=True)),
                ('schema', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='ready', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_artifacts', to='datasets.dataset')),
                ('dataset_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layer_artifacts', to='data_platform.datasetversion')),
                ('storage_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='layer_artifacts', to='storage.storageobject')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_platform_layer_artifacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LineageRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('source_type', models.CharField(max_length=64)),
                ('source_id', models.UUIDField()),
                ('target_type', models.CharField(max_length=64)),
                ('target_id', models.UUIDField()),
                ('transformation', models.CharField(default='ingest', max_length=128)),
                ('layer', models.CharField(blank=True, choices=[('landing', 'Landing Zone'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_platform_lineage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=32)),
                ('current_layer', models.CharField(blank=True, choices=[('landing', 'Landing Zone'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('stages_completed', models.JSONField(blank=True, default=list)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_runs', to='datasets.dataset')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_runs', to='jobs.job')),
                ('source_storage_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_runs_as_source', to='storage.storageobject')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_platform_pipeline_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CatalogEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('current_layer', models.CharField(choices=[('landing', 'Landing Zone'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='landing', max_length=16)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('search_text', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_entry', to='datasets.dataset')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_entries_owned', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_platform_catalog',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['organization_id', '-updated_at'], name='idx_dp_catalog_org'), models.Index(fields=['organization_id', 'is_published'], name='idx_dp_catalog_pub')],
            },
        ),
        migrations.AddIndex(
            model_name='datasetversion',
            index=models.Index(fields=['organization_id', 'dataset', '-version_number'], name='idx_dp_version_org_ds'),
        ),
        migrations.AddConstraint(
            model_name='datasetversion',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('dataset', 'version_number'), name='uniq_dataset_version_alive'),
        ),
        migrations.AddIndex(
            model_name='layerartifact',
            index=models.Index(fields=['dataset', 'layer', '-created_at'], name='idx_dp_layer_ds_layer'),
        ),
        migrations.AddIndex(
            model_name='lineagerecord',
            index=models.Index(fields=['source_type', 'source_id'], name='idx_dp_lineage_src'),
        ),
        migrations.AddIndex(
            model_name='lineagerecord',
            index=models.Index(fields=['target_type', 'target_id'], name='idx_dp_lineage_tgt'),
        ),
    ]
